### ISSUE TITLE
No plain Exceptions

### ISSUE THREAD

**Issue by evanp** [fuzzy-io/python#2]
Do a subclass for the missing API key exception.

**Comment by sfllaw** [comment]
Make sure it subclasses the right standard exception. For instance, an incorrect API key exception is probably a class InvalidApiKeyError(RuntimeError). And really, you should just be testing:

```
  if not api_key:
      raise InvalidApiKeyError("Missing API key: {!r}".format(api_key))
```

Obviously, empty keys make no sense. And if the user wants to implement something that returns true and can be has a `str` representation that works as an API key, don't bother restricting it.
